theme: minima
title: Fabio Perrella's Blog
header_pages:
  - about.md
  - talks.md
  - opensource.md
twitter_username: fabioperrella
linkedin_username: fabio-perrella-8247976
github_username: fabioperrella
disqus:
    shortname: fabioperrella
minima:
  date_format: "%b %-d, %Y"
show_excerpts: true
relative_links:
  enabled: true
  collections: true
google_analytics: UA-158992279-1
plugins:
  - jekyll-redirect-from
